
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>VervPalMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
	<Reference Include="AltLibrary">
		<HintPath>..\ModAssemblies\AltLibrary_v1.2.dll</HintPath>
	</Reference>
    <Reference Include="AltLibrary">
      <HintPath>..\ModAssemblies\AltLibrary_v2.0.2.2.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>