
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>VervPalMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
	<Reference Include="AltLibrary">
		<HintPath>..\ModAssemblies\AltLibrary_v2.1.dll</HintPath>
	</Reference>
  </ItemGroup>
</Project>